export const AJAX_REQUESTING = 'AJAX_REQUESTING'
export const AJAX_REQUESTED = 'AJAX_REQUESTED'
export const AJAX_REQUESTERROR = 'AJAX_REQUESTERROR' 
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING' 
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED' 
export const LOGIN_REQUESTERROR = 'LOGIN_REQUESTERROR' 
export const REGISTER_REQUESTING = 'REGISTER_REQUESTING' 
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED' 
export const REGISTER_REQUESTERRO = 'REGISTER_REQUESTERRO'
export const CHANGE_REQUESTING = 'CHANGE_REQUESTING'
export const CHANGE_REQUESTED = 'CHANGE_REQUESTED'
export const CHANGE_REQUESTERRO = 'CHANGE_REQUESTERRO'



