export const GETSTRATEGY_REQUESTING ='GETSTRATEGY_REQUESTING';
export const GETSTRATEGY_REQUESTED = 'GETSTRATEGY_REQUESTED';
export const GETSTRATEGY_ERROR = 'GETSTRATEGY_ERROR';

export const GETPAGE_REQUESTING = 'GETPAGE_REQUESTING';
export const GETPAGE_REQUESTED = 'GETPAGE_REQUESTED';
export const GETPAGE_ERROR = 'GETPAGE_ERROR';
