export const ORDER_REQUESTING ='ORDER_REQUESTING';
export const ORDER_REQUESTED = 'ORDER_REQUESTED';
export const ORDER_ERROR = 'ORDER_ERROR';

export const TYPE_REQUESTING ='TYPE_REQUESTING';
export const TYPE_REQUESTED = 'TYPE_REQUESTED';
export const TYPE_ERROR = 'TYPE_ERROR';

export const COMMON_REQUESTING ='COMMON_REQUESTING';
export const COMMON_REQUESTED = 'COMMON_REQUESTED';
export const COMMON_ERROR = 'COMMON_ERROR';