export const GETRELEASE_REQUESTING ='GETRELEASE_REQUESTING';
export const GETRELEASE_REQUESTED = 'GETRELEASE_REQUESTED';
export const GETRELEASE_ERROR = 'GETRELEASE_ERROR';

export const DELETERELEASE_REQUESTING ='DELETERELEASE_REQUESTING';
export const DELETERELEASE_REQUESTED = 'DELETERELEASE_REQUESTED';
export const DELETERELEASE_ERROR = 'DELETERELEASE_ERROR';