export const GETSTRATEGY_REQUESTING ='GETSTRATEGY_REQUESTING';
export const GETSTRATEGY_REQUESTED = 'GETSTRATEGY_REQUESTED';
export const GETSTRATEGY_ERROR = 'GETSTRATEGY_ERROR';

export const GETHOTEL_REQUESTING='GETHOTEL_REQUESTING';
export const GETHOTEL_REQUESTED='GETHOTEL_REQUESTED';
export const GETHOTEL_ERROR='GETHOTEL_ERROR';